apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-ex
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/\skcloud2007/ocp-devsecops.git
    targetRevision: main
    path: gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: devsecops-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
